# Generated by Django 4.2.2 on 2024-02-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="age",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="height",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="weight",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
